### ISSUE TITLE
oVirtBackup stop working after update to oVirt 4.2.7

### ISSUE THREAD

**Issue by pontostroy** [wefixit-AT/oVirtBackup#55]
ovirt-engine-extensions-tool aaa login-user --profile=domain --user-name=backupuser

works as before
but ovirt backup can't authorized

Traceback (most recent call last):
  File "./backup.py", line 404, in <module>
    main(sys.argv[1:])
  File "./backup.py", line 212, in main
    connect()
  File "./backup.py", line 400, in connect
    debug=False
  File "/home/pontostroy/.local/lib/python2.7/site-packages/ovirtsdk/api.py", line 191, in __init__
    url=''
  File "/home/pontostroy/.local/lib/python2.7/site-packages/ovirtsdk/infrastructure/proxy.py", line 122, in request
    persistent_auth=self.__persistent_auth
  File "/home/pontostroy/.local/lib/python2.7/site-packages/ovirtsdk/infrastructure/connectionspool.py", line 79, in do_request
    persistent_auth)
  File "/home/pontostroy/.local/lib/python2.7/site-packages/ovirtsdk/infrastructure/connectionspool.py", line 162, in __do_request
    raise errors.RequestError(response_code, response_reason, response_body)
ovirtsdk.infrastructure.errors.RequestError:
status: 401
reason: Unauthorized
detail: 
<html><head><title>Error</title></head><body>Unauthorized</body></htm

**Comment by wefixit-AT** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.
