### ISSUE TITLE
TypeError: The 'search' parameter should be of type 'str', but it is of type 'unicode'.

### ISSUE THREAD

**Issue by pureinfosystems** [wefixit-AT/oVirtBackup#71]
I am using version 4.3 script to backup 4.3 ovirt environment but received following error.

Traceback (most recent call last):
  File "/opt/ovirtbackup/backup.py", line 464, in <module>
    main(sys.argv[1:])
  File "/opt/ovirtbackup/backup.py", line 223, in main
    if  system_service.data_centers_service().list(search='name=%s' % config.get_datacenter_name() )[0] is None:
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/services.py", line 6507, in list
    ('search', search, str),
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 191, in _check_types
    raise TypeError(' '.join(messages))
TypeError: The 'search' parameter should be of type 'str', but it is of type 'unicode'.

**Comment by tatref** [comment]
Probably because of python2.7, which handles string differently than python3

See #78 for fix

**Comment by pureinfosystems** [comment]
After I updated the backup.py with suggested changes, I continue to receive following error.

Traceback (most recent call last):
  File "./backup.py", line 466, in <module>
    main(sys.argv[1:])
  File "./backup.py", line 223, in main
    if  system_service.data_centers_service().list(search='name=%s' % config.get_datacenter_name() )[0] is None:
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/services.py", line 6507, in list
    ('search', search, str),
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 191, in _check_types
    raise TypeError(' '.join(messages))
TypeError: The 'search' parameter should be of type 'str', but it is of type 'unicode'.
